INSERT INTO GENERO VALUES (1, 'Sports');
INSERT INTO GENERO VALUES (2, 'RPG');
INSERT INTO GENERO VALUES (3, 'Races');
INSERT INTO GENERO VALUES (4, 'Action');
INSERT INTO GENERO VALUES (5, 'Fights');
INSERT INTO GENERO VALUES (6, 'Puzzles');
INSERT INTO GENERO VALUES (7, 'Adventure');

INSERT INTO CONSOLAS VALUES (1, 'Playstation 4');
INSERT INTO CONSOLAS VALUES (2, 'Nintendo Switch');
INSERT INTO CONSOLAS VALUES (3, 'Xbox One');
INSERT INTO CONSOLAS VALUES (4, 'Playstation 5');
INSERT INTO CONSOLAS VALUES (5, 'Xbox Series X');

INSERT INTO VIDEOJUEGOS VALUES (1, 'Elden Ring', 2, 5, 10, 1);
INSERT INTO VIDEOJUEGOS VALUES (2, 'Kirby and the Forgotten Land', 7, 2, 15, 2);
INSERT INTO VIDEOJUEGOS VALUES (3, 'LEGO Star Wars: The Skywalker Saga', 4, 1, 13, 3);
INSERT INTO VIDEOJUEGOS VALUES (4, 'Horizon Forbidden West Launch Edition', 7, 4, 12, 4);
INSERT INTO VIDEOJUEGOS VALUES (5, 'Ratchet and Clank: Rift Apart', 7, 4, 11, 5);
INSERT INTO VIDEOJUEGOS VALUES (6, 'Marvel Spider-Man: Miles Morales', 7, 4, 7, 6);
INSERT INTO VIDEOJUEGOS VALUES (7, 'Forza Horizon 5', 3, 5, 20,7);

INSERT INTO PRODUCTOS VALUES (1, 'GameStart Gift Card - €25', 150, 8);
INSERT INTO PRODUCTOS VALUES (2, 'GameStart Gift Card - €50', 50, 9);
INSERT INTO PRODUCTOS VALUES (3, 'GameStart Gift Card - €100', 20, 10);
INSERT INTO PRODUCTOS VALUES (4, 'Oculus Quest 2', 15, 11);
INSERT INTO PRODUCTOS VALUES (5, 'PlayStation Store Gift Card €50', 15, 12);
INSERT INTO PRODUCTOS VALUES (6, 'PlayStation Store Gift Card €100', 15, 13);

INSERT INTO LISTAPRECIO VALUES (1, 56.99),
INSERT INTO LISTAPRECIO VALUES (2, 59.99),
INSERT INTO LISTAPRECIO VALUES (3, 59.99);
INSERT INTO LISTAPRECIO VALUES (4, 69.99);
INSERT INTO LISTAPRECIO VALUES (5, 49.99);
INSERT INTO LISTAPRECIO VALUES (6, 49.99);
INSERT INTO LISTAPRECIO VALUES (7, 50.99);
INSERT INTO LISTAPRECIO VALUES (8, 25);
INSERT INTO LISTAPRECIO VALUES (9, 50);
INSERT INTO LISTAPRECIO VALUES (10, 100);
INSERT INTO LISTAPRECIO VALUES (11, 399.99);
INSERT INTO LISTAPRECIO VALUES (12, 50);
INSERT INTO LISTAPRECIO VALUES (13, 100);

INSERT INTO SOCIOS VALUES ('87654321A', 'Arnau Barra', 'arnau@yahoo.com', 605442228);
INSERT INTO SOCIOS VALUES ('17350975Z', 'Matias Lazo', 'matias.L@gmail.com', 643447223);
INSERT INTO SOCIOS VALUES ('25312378Y', 'Tomas Lopez', 'tomaslm@gmail.com', 897642143);
INSERT INTO SOCIOS VALUES ('12345678X', 'Marc Taberner', 'marc@hotmail.com', 509742277);